version: '3'
services:
  web:
    working_dir: /epm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/epm"
    command: 'bundle exec rackup -p 4567 --host "0.0.0.0"'
    ports:
      - '4567:4567'
